import {
    apiServices,
    apiHooks,
    userApi,
    roleApi,
    leadApi,
    contactApi,
    pipelineApi,
    stageApi,
    filterApi,
    proposalApi,
    designationApi,
    employeeApi,
    departmentApi,
    teamMemberApi,
    noteApi,
    projectApi,
    activityApi,
    holidayApi,
    leaveApi,
    taskApi,
    followupApi,
    milestoneApi,
    milestoneTaskApi,
    maintenanceApi,
    attendanceApi,
    companyDetailsApi,
    reminderApi,
    settingApi,
    inquiryApi,
    companyApi,
    planApi,
    adminApi
} from './apiServicesImpl.js';

export const apiServiceNames = [
    'user', 'role', 'lead', 'contact', 'pipeline', 'stage', 'filter', 'proposal','designation', 'employee', 'department', 'teamMember', 'note', 'project', 'activity', 'holiday', 'leave', 'task', 'milestone', 'milestoneTask', 'followup', 'maintenance', 'attendance', 'companyDetails', 'reminder', 'setting', 'inquiry', 'company', 'plan', 'admin'
];

export {
    userApi,
    roleApi,
    leadApi,
    contactApi,
    pipelineApi,
    stageApi,
    filterApi,
    proposalApi,
    designationApi,
    employeeApi,
    departmentApi,
    teamMemberApi,
    noteApi,
    projectApi,
    activityApi,
    holidayApi,
    leaveApi,
    taskApi,
    followupApi,
    milestoneApi,
    milestoneTaskApi,
    maintenanceApi,
    attendanceApi,
    companyDetailsApi,
    reminderApi,
    settingApi,
    inquiryApi,
    companyApi,
    planApi,
    adminApi
};

export const {
    useGetCompanyDetailsQuery, useGetCompanyDetailQuery, useCreateCompanyDetailsMutation, useUpdateCompanyDetailsMutation, useDeleteCompanyDetailsMutation,
    useGetRolesQuery, useGetRoleQuery, useCreateRoleMutation, useUpdateRoleMutation, useDeleteRoleMutation,
    useGetLeadsQuery, useGetLeadQuery, useCreateLeadMutation, useUpdateLeadMutation, useDeleteLeadMutation,
    useGetContactsQuery, useGetContactQuery, useCreateContactMutation, useUpdateContactMutation, useDeleteContactMutation,
    useGetPipelinesQuery, useGetPipelineQuery, useCreatePipelineMutation, useUpdatePipelineMutation, useDeletePipelineMutation,
    useGetStagesQuery, useGetStageQuery, useCreateStageMutation, useUpdateStageMutation, useDeleteStageMutation,
    useGetFiltersQuery, useGetFilterQuery, useCreateFilterMutation, useUpdateFilterMutation, useDeleteFilterMutation,
    useGetProposalsQuery, useGetProposalQuery, useCreateProposalMutation, useUpdateProposalMutation, useDeleteProposalMutation,
    useGenerateProposalPDFQuery, useSendProposalMutation,
    useGetDesignationsQuery, useGetDesignationQuery, useCreateDesignationMutation, useUpdateDesignationMutation, useDeleteDesignationMutation,
    useGetEmployeesQuery, useGetEmployeeQuery, useCreateEmployeeMutation, useUpdateEmployeeMutation, useDeleteEmployeeMutation,
    useGetDepartmentsQuery, useGetDepartmentQuery, useCreateDepartmentMutation, useUpdateDepartmentMutation, useDeleteDepartmentMutation,
    useGetTeamMembersQuery, useGetTeamMemberQuery, useCreateTeamMemberMutation, useUpdateTeamMemberMutation, useDeleteTeamMemberMutation,
    useGetNotesQuery, useGetNoteQuery, useCreateNoteMutation, useUpdateNoteMutation, useDeleteNoteMutation,
    useGetClientsQuery, useGetClientQuery, useCreateClientMutation, useUpdateClientMutation, useDeleteClientMutation,
    useGetProjectsQuery, useGetProjectQuery, useCreateProjectMutation, useUpdateProjectMutation, useDeleteProjectMutation,
    useGetMilestonesQuery, useGetMilestoneQuery, useCreateMilestoneMutation, useUpdateMilestoneMutation, useDeleteMilestoneMutation,
    useGetMilestoneTasksQuery, useGetMilestoneTaskQuery, useCreateMilestoneTaskMutation, useUpdateMilestoneTaskMutation, useDeleteMilestoneTaskMutation,
    useGetFollowupsQuery, useGetFollowupQuery, useCreateFollowupMutation, useUpdateFollowupMutation, useDeleteFollowupMutation,
    useGetMaintenancesQuery, useGetMaintenanceQuery, useCreateMaintenanceMutation, useUpdateMaintenanceMutation, useDeleteMaintenanceMutation,
    useGetAttendancesQuery, useGetAttendanceQuery, useCreateAttendanceMutation, useUpdateAttendanceMutation, useDeleteAttendanceMutation,
    useGetHolidaysQuery, useGetHolidayQuery, useCreateHolidayMutation, useUpdateHolidayMutation, useDeleteHolidayMutation,
    useGetLeavesQuery, useGetLeaveQuery, useCreateLeaveMutation, useUpdateLeaveMutation, useDeleteLeaveMutation,
    useGetRemindersQuery, useGetReminderQuery, useCreateReminderMutation, useUpdateReminderMutation, useDeleteReminderMutation,
    useGetTasksQuery, useGetTaskQuery, useCreateTaskMutation, useUpdateTaskMutation, useDeleteTaskMutation,
    useGetActivitiesQuery, useGetActivityQuery, useCreateActivityMutation, useUpdateActivityMutation, useDeleteActivityMutation,
    useGetBranchesQuery, useGetBranchQuery, useCreateBranchMutation, useUpdateBranchMutation, useDeleteBranchMutation,
    useGetFilesQuery, useGetFileQuery, useCreateFileMutation, useUpdateFileMutation, useDeleteFileMutation,
    useGetNotificationsQuery, useGetNotificationQuery, useCreateNotificationMutation, useUpdateNotificationMutation, useDeleteNotificationMutation,
    useGetPermissionsQuery, useGetPermissionQuery, useCreatePermissionMutation, useUpdatePermissionMutation, useDeletePermissionMutation,
    useGetTemplatesQuery, useGetTemplateQuery, useCreateTemplateMutation, useUpdateTemplateMutation, useDeleteTemplateMutation,
    useGetTranslationsQuery, useGetTranslationQuery, useCreateTranslationMutation, useUpdateTranslationMutation, useDeleteTranslationMutation,
    useGetVersionsQuery, useGetVersionQuery, useCreateVersionMutation, useUpdateVersionMutation, useDeleteVersionMutation,
    useGetWorkflowsQuery, useGetWorkflowQuery, useCreateWorkflowMutation, useUpdateWorkflowMutation, useDeleteWorkflowMutation,
    useGetSettingsQuery, useGetSettingQuery, useCreateSettingsMutation, useUpdateSettingsMutation, useDeleteSettingsMutation,
    useGetInquiriesQuery, useGetInquiryQuery, useCreateInquiryMutation, useUpdateInquiryMutation, useDeleteInquiryMutation,
    useGetCompaniesQuery, useGetCompanyQuery, useCreateCompanyMutation, useUpdateCompanyMutation, useDeleteCompanyMutation,
    useGetPlansQuery, useGetPlanQuery, useCreatePlanMutation, useUpdatePlanMutation, useDeletePlanMutation,
    useGetActivePlansQuery, useGetDefaultPlanQuery, useGetTrialPlanQuery,
    useGetAdminsQuery, useGetAdminQuery, useCreateAdminMutation, useUpdateAdminMutation, useDeleteAdminMutation
} = apiHooks;

export { apiServices, apiHooks };